# Generated by Django 2.0.13 on 2020-08-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180809_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('W', 'Weekly'), ('M', 'Monthly')], help_text='Does this event occur weekly or monthly', max_length=1, null=True),
        ),
    ]
