config = dict(
   port='8015',
   app_dir='klab',
   friendly_name='kLab',
   name='klab',
   repo='klab',
   user='klab',
   env='env',
   settings='settings.py.dev',
   db='klab',
   db_user='klab',
   db_host='localhost',
   custom_domains='www.klab.rw klab.rw')
