# Generated by Django 2.0.13 on 2020-08-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180809_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applying_for',
            field=models.CharField(choices=[('G', 'Green - kLab Tenant'), ('B', 'Blue - kLab Mentor')], help_text='The type of membership you are applying for', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'A few times a week'), ('M', 'A few times a month')], help_text='How often you plan on visiting kLab', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='location',
            field=models.CharField(choices=[('KIGALI', 'Kigali'), ('KIGALI/KINYINYA', 'Kigali Kinyinya (For under 15 years ONLY)'), ('KARONGI', 'Karongi'), ('RUBAVU', 'Rubavu'), ('RUSIZI', 'Rusizi'), ('MUSANZE', 'Musanze'), ('HUYE', 'Huye'), ('MUHANGA', 'Muhanga'), ('NYAGATARE', 'Nyagatare'), ('RWAMAGANA', 'Rwamagana')], default='KIGALI', help_text='kLab location your are applying for.', max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='professional_status',
            field=models.CharField(choices=[('STU', 'Student'), ('ENT', 'Entrepreneur'), ('EIT', 'Employed in IT'), ('NIT', 'Employed in non-IT'), ('UNE', 'Not currently employed')], help_text='Your professional background', max_length=3),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('G', 'Green - kLab Tenant'), ('B', 'Blue - kLab Mentor'), ('R', 'Red - kLab Core Team')], help_text='The type of membership', max_length=1),
        ),
    ]
